In [1]:
import torch
import numpy as np

In [4]:
!nvidia-smi


Thu Aug 19 22:28:26 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1650    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   43C    P8     3W /  N/A |    581MiB /  3910MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
torch.ones(1,4)

tensor([[1., 1., 1., 1.]])

In [15]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [17]:
my_tensor = torch.rand(3,2)
my_tensor # from normal distribution

tensor([[0.1516, 0.9831],
        [0.6976, 0.6300],
        [0.6265, 0.4071]])

In [18]:
my_tensor.device

device(type='cpu')

In [10]:
my_tensor.mul(my_tensor)

tensor([[0.0152, 0.0666, 0.3035, 0.0014, 0.7687],
        [0.4332, 0.1302, 0.0847, 0.0120, 0.0087],
        [0.0326, 0.7096, 0.6844, 0.0330, 0.0163]])

## DIM 0 means column wise
## DIM 1 means row wise

In [20]:
torch.nn.functional.softmax(my_tensor,dim=1) # dim 0 means column wise
                                            # dim 1 means row wise

tensor([[0.3033, 0.6967],
        [0.5169, 0.4831],
        [0.5546, 0.4454]])

In [23]:
# clip anything below 0.3 to 0.3 and above 0.9 to 0.9
my_tensor.clip(0.3,0.9)

tensor([[0.3000, 0.9000],
        [0.6976, 0.6300],
        [0.6265, 0.4071]])

In [24]:
my_tensor.detach().numpy()

array([[0.1516177 , 0.98305506],
       [0.6975581 , 0.6300055 ],
       [0.6264709 , 0.40710622]], dtype=float32)

## BEST LINK for Tensor Operation https://pytorch.org/docs/stable/tensors.html