In [44]:
import torch
a = torch.tensor([4.],requires_grad=True)

In [45]:
b= torch.tensor([6.],requires_grad=True)

In [46]:
y = a**3 - b**2

In [47]:
y

tensor([28.], grad_fn=<SubBackward0>)

In [48]:
# dy/da = 3a**2 = 48
# dy/db = -2b = -10

### Now to calculate these grads
### just do

# y.backward()

In [49]:
y.backward()

In [50]:
print(a.grad)
print(b.grad)

tensor([48.])
tensor([-12.])


## Example

In [51]:
W = torch.randn(10,1,requires_grad=True)

b = torch.randn(1,requires_grad=True)

In [52]:
x = torch.rand(1,10,requires_grad=True)

output = torch.matmul(x,W)+b

In [53]:
# say loss is 

loss  = 1-output


In [54]:
output

tensor([[-0.2163]], grad_fn=<AddBackward0>)

### Now once I click on .backward() function

### all gradients will get stored in .grad attribute of variable

In [55]:

loss.backward()

In [56]:
W.grad

tensor([[-0.8336],
        [-0.3989],
        [-0.0133],
        [-0.9430],
        [-0.0670],
        [-0.3587],
        [-0.2237],
        [-0.5415],
        [-0.0401],
        [-0.4186]])

In [57]:
b.grad

tensor([-1.])

In [58]:
# Update the weights

# Menaning of torch.no_grad()  https://forums.fast.ai/t/what-does-torch-no-grad-mean/72355


# This is just 1 epoch
learning_rate = 0.001
with torch.no_grad():
    W = W - learning_rate*W.grad.data
    print(W)

tensor([[ 1.0123],
        [-0.2299],
        [-2.0099],
        [-0.8471],
        [-1.8105],
        [-0.8976],
        [-0.0164],
        [-1.1297],
        [ 2.2109],
        [-0.3522]])
